### ISSUE TITLE
'Variable type field must be a TensorType.' error when running cell2location

### ISSUE THREAD

**Issue by sztankatt** [BayraktarLab/cell2location#27] opened 2021-02-19 22:26 UTC
Hi, 

I've followed the tutorial, however I'm stack during the last part of 2/3. When I run the code above, I get an error.
    
    os.environ["THEANO_FLAGS"] = 'device=cpu,floatX=float32,openmp=True,force_device=True'
    r = cell2location.run_cell2location(

          # Single cell reference signatures as pd.DataFrame
          # (could also be data as anndata object for estimating signatures
          #  as cluster average expression - `sc_data=adata_snrna_raw`)
          sc_data=inf_aver,
          # Spatial data as anndata object
          sp_data=adata_vis,

          # the column in sc_data.obs that gives cluster idenitity of each cell
          summ_sc_data_args={'cluster_col': "TaxonomyRank4",
                             # select marker genes of cell types by specificity of their expression signatures
                             'selection': "cluster_specificity",
                             # specificity cutoff (1 = max, 0 = min)
                             'selection_specificity': 0.5
                            },

          train_args={'use_raw': True, # By default uses raw slots in both of the input datasets.
                      'n_iter': 40000, # Increase the number of iterations if needed (see QC below)

                      # Whe analysing the data that contains multiple experiments,
                      # cell2location automatically enters the mode which pools information across experiments
                      'sample_name_col': 'sample'}, # Column in sp_data.obs with experiment ID (see above)

          export_args={'path': data_dir + 'cell2location_model/'
                      }

    )

And the error what I get is:

```
### Summarising single cell clusters ###
### Creating model ### - time 0.0 min
Traceback (most recent call last):
  File "run_cell2location.py", line 191, in <module>
    export_args={'path': data_dir + 'cell2location_model/'
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/cell2location/run_c2l.py", line 345, in run_cell2location
    **model_kwargs)
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/cell2location/models/LocationModelLinearDependentWMultiExperiment.py", line 278, in __init__
    total_size=self.X_data.shape)
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 83, in __new__
    return model.Var(name, dist, data, total_size, dims=dims)
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/pymc3/model.py", line 1117, in Var
    model=self,
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/pymc3/model.py", line 1737, in __init__
    data = as_tensor(data, name, model, distribution)
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/pymc3/model.py", line 1691, in as_tensor
    data = tt.as_tensor_variable(data, name=name)
  File "/home/tsztank/miniconda3/envs/cellpymc/lib/python3.7/site-packages/theano/tensor/basic.py", line 158, in as_tensor_variable
    "Variable type field must be a TensorType.", x, x.type)
theano.tensor.var.AsTensorError: ('Variable type field must be a TensorType.', SparseVariable{csr,int16}, Sparse[int16, csr])
```

**Comment by vitkl** [comment] 2021-02-21 14:28
Hi @sztankatt 

Thanks for using cell2location! 

1. We generally recommend using GPU unless you have a small spatial dataset with e.g. < 100 locations / multi-cell samples (for example @AlexanderAivazidis recently added a notebook showing how to analyse Nanostring WTA data https://github.com/BayraktarLab/cell2location/blob/master/docs/notebooks/cell2loation_for_NanostringWTA.ipynb). Training for the data in the tutorial notebook (2 sections of mouse brain Visium) is going to take >100 hours on CPU but just 25 minutes on GPU. We are working on porting cell2location to numpyro (https://github.com/vitkl/cell2location_numpyro) and pyro that have better CPU performance (hours for demo notebook) but there will always be substantial speedup from using the GPU.

2. With regard to the error you are getting, 
    A) If you can share just a few (e.g. 10) observations from your `adata_vis` and a subset of `inf_aver` this will help reproduce the error (e.g. by email vitalii.kleshchevnikov@sanger.ac.uk).
    B) Could you please print out the type of objects `type(inf_aver)`, `type(adata_vis.raw.X)`
    C) Could you tell which cell2location version you are using (e.g. latest github / singularity container)?

**Comment by lopollar** [comment] 2021-03-03 16:13
Hi, 
I am trying to run through th whole tutorial of cell2location on the data provided by the tutorial before trying it on my own data. I however, encounter problems when arriving at running the actual model. when running:
```
sc.settings.set_figure_params(dpi = 100, color_map = 'viridis', dpi_save = 100,
                              vector_friendly = True, format = 'pdf',
                              facecolor='white')

r = cell2location.run_cell2location(

      # Single cell reference signatures as pd.DataFrame
      # (could also be data as anndata object for estimating signatures
      #  as cluster average expression - `sc_data=adata_snrna_raw`)
      sc_data=inf_aver,
      # Spatial data as anndata object
      sp_data=adata_vis,

      # the column in sc_data.obs that gives cluster idenitity of each cell
      summ_sc_data_args={'cluster_col': "annotation_1",
                         # select marker genes of cell types by specificity of their expression signatures
                         'selection': "cluster_specificity",
                         # specificity cutoff (1 = max, 0 = min)
                         'selection_specificity': 0.07
                        },

      train_args={'use_raw': True, # By default uses raw slots in both of the input datasets.
                  'n_iter': 40000, # Increase the number of iterations if needed (see QC below)

                  # Whe analysing the data that contains multiple experiments,
                  # cell2location automatically enters the mode which pools information across experiments
                  'sample_name_col': 'sample'}, # Column in sp_data.obs with experiment ID (see above)


      export_args={'path': results_folder, # path where to save results
                   'run_name_suffix': '' # optinal suffix to modify the name the run
                  },

      model_kwargs={ # Prior on the number of cells, cell types and co-located groups

                    'cell_number_prior': {
                        # - N - the expected number of cells per location:
                        'cells_per_spot': 8,
                        # - A - the expected number of cell types per location:
                        'factors_per_spot': 9,
                        # - Y - the expected number of co-located cell type groups per location
                        'combs_per_spot': 5
                    },

                     # Prior beliefs on the sensitivity of spatial technology:
                    'gene_level_prior':{
                        # Prior on the mean
                        'mean': 1/2,
                        # Prior on standard deviation,
                        # a good choice of this value should be at least 2 times lower that the mean
                        'sd': 1/4
                    }
      }
)
```
I encounter following error, the same type as mentioned above: 
```
---------------------------------------------------------------------------
AsTensorError                             Traceback (most recent call last)
<ipython-input-28-5578f54fa95f> in <module>
     49                         # Prior on standard deviation,
     50                         # a good choice of this value should be at least 2 times lower that the mean
---> 51                         'sd': 1/4
     52                     }
     53       }

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/cell2location/run_c2l.py in run_cell2location(sc_data, sp_data, model_name, verbose, show_locations, return_all, summ_sc_data_args, train_args, model_kwargs, posterior_args, export_args)
    343                 fact_names=fact_names,
    344                 sample_id=sp_data.obs[train_args['sample_name_col']],
--> 345                 **model_kwargs)
    346 
    347     ####### Print run name #######

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/cell2location/models/LocationModelLinearDependentWMultiExperiment.py in __init__(self, cell_state_mat, X_data, n_comb, data_type, n_iter, learning_rate, total_grad_norm_constraint, verbose, var_names, var_names_read, obs_names, fact_names, sample_id, gene_level_prior, gene_level_var_prior, cell_number_prior, cell_number_var_prior, phi_hyp_prior, spot_fact_mean_var_ratio, exper_gene_level_mean_var_ratio)
    276                                                                      1 / tt.pow(self.gene_E, 2)),
    277                                                    observed=self.x_data,
--> 278                                                    total_size=self.X_data.shape)
    279 
    280             # =====================Compute nUMI from each factor in spots  ======================= #

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/pymc3/distributions/distribution.py in __new__(cls, name, *args, **kwargs)
     81         else:
     82             dist = cls.dist(*args, **kwargs)
---> 83         return model.Var(name, dist, data, total_size, dims=dims)
     84 
     85     def __getnewargs__(self):

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/pymc3/model.py in Var(self, name, dist, data, total_size, dims)
   1115                     distribution=dist,
   1116                     total_size=total_size,
-> 1117                     model=self,
   1118                 )
   1119             self.observed_RVs.append(var)

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/pymc3/model.py in __init__(self, type, owner, index, name, data, distribution, total_size, model)
   1735 
   1736         if distribution is not None:
-> 1737             data = as_tensor(data, name, model, distribution)
   1738 
   1739             self.missing_values = data.missing_values

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/pymc3/model.py in as_tensor(data, name, model, distribution)
   1689         return data
   1690     else:
-> 1691         data = tt.as_tensor_variable(data, name=name)
   1692         data.missing_values = None
   1693         return data

/srv/scratch/lottep/anaconda3/envs/cellpymc2/lib/python3.7/site-packages/theano/tensor/basic.py in as_tensor_variable(x, name, ndim)
    156         if not isinstance(x.type, TensorType):
    157             raise AsTensorError(
--> 158                 "Variable type field must be a TensorType.", x, x.type)
    159 
    160         if ndim is None:

AsTensorError: ('Variable type field must be a TensorType.', SparseVariable{csr,int16}, Sparse[int16, csr])
```
I run the model on an 'old' titan X GPU, as newer GPU's don't support theano anymore.
I installed the package yesterday, based on the environment.yml file provided, and then using the github as mentioned by you. 

However, I encountered a problem with the arviz package. When loading the package in python, I received following error: 
module 'arviz' has no attribute 'geweke'
For this reason, I installed arviz version 0.10.0 instead of 0.11.2. This made it possible to load the package into python. 
If necessary, I can send more information, but I just followed all provided steps.

**Comment by onahman** [comment] 2021-03-03 18:27
I did exactly the same as @lopollar, and I am getting the same error as he is.
I also tried to take only one sample for the spatial data and erased the 'sample_name_col': 'sample'.
At first I got an error that 'LocationModelLinearDependentW' is not defined in  cell2location.models. I added it to the models  __init__.py and then received the same error (AsTensorError) again.
So it is probably not specific to the model and please also check the case for one sample.

**Comment by sztankatt** [comment] 2021-03-04 08:41
Dear @vitkl 

A) I'll send the data as you ask 
B) 
```
print(type(adata_vis.raw.X))
print(type(inf_aver))```
results in 
```
<class 'scipy.sparse.csr.csr_matrix'>
<class 'pandas.core.frame.DataFrame'>
```

**Comment by vitkl** [comment] 2021-03-04 11:07
Hi @lopollar @sztankatt  @onahman!

thanks for using cell2location! Is using **docker/singularity** **container** an option for you? We recommend using the containers to avoid version incompatibility issues such as that you are facing now.

Pymc3 and related packages (arviz, theano from pymc3 developers) have undergone major changes recently and , unfortunately, I was not able to adapt cell2location to those changes just yet, sorry. I will likely do that within the next 2-3 weeks.

@lopollar thanks for pointing out the arviz version issue! Also: 

> as newer GPU's don't support theano anymore

This is not true - I use Tesla V100 / P100 all the time. The issue might be in the latest drivers rather than hardware. Using the containers we provide should help with this issue.

@onahman Sorry for this issue. Using the containers should resolve it. I also just introduced changes that should address it in https://github.com/BayraktarLab/cell2location/commit/d4c4e7f0407af6c9c19a64334e094dafcfe3114e .

**Comment by onahman** [comment] 2021-03-04 11:29
@vitkl Thank you for the fast reply!
Is it possible to create a conda / virtual env with the compatible versions?
I am reluctant to move to a docker.. I don't know how it affects performance, but I assume it does and I am not sure how long it will take to set up the GPU in there.

**Comment by vitkl** [comment] 2021-03-04 11:36
@onahman It should be possible but it will take some trial and error which I cannot do this week. If you decide to do that would be great if you can contribute back.

On performance, 1) the container will not affect training speed; 2) the accuracy of cell2location was tested using driver versions in the container (e.g. CUDA 10.2) - but I would not expect substantial difference with new drivers.

On setting up GPU, I am actually not an expert on setting up this (central institute IT setup singularity for us). Maybe @yozhikoff can help?

**Comment by vitkl** [comment] 2021-03-04 12:05
@sztankatt I can confirm that your issue is also because of incompatible dependency versions. Cell2location works on your data with our singularity container. Is it possible for you to use the container?

Also, just as a side note, since you are using a technology with a different spatial resolution, I would recommend adjusting these prior accordingly:

```
'cell_number_prior': {
                        # - N - the expected number of cells per location (1 cell for 10um locations):
                        'cells_per_spot': 8, 
                        # - A - the expected number of cell types per location (also 1 for 10um locations):
                        'factors_per_spot': 9, 
                        # - Y - the expected number of co-located cell type groups per location (also 1 for 10um locations)
                        'combs_per_spot': 5
                    },
          
                     # Prior beliefs on the sensitivity of spatial technology (you need to compare the total count per location to snRNA-seq):
                    'gene_level_prior':{
                        # Prior on the mean
                        'mean': 1/2, 
                        # Prior on standard deviation,
                        # a good choice of this value should be at least 2 times lower that the mean
                        'sd': 1/4
                    }
```

Also, if you want to use cell2location plotting (such as automatic plotting for all cell type in `cell2location.run_cell2location`) or general scanpy plotting - you need to add 
1) `adata.obsm['spatial']` slot with X and Y coordinates;
2) `sp_data.uns['spatial'] = {'wt_1': 'random letters', 'wt_2': 'random letters', ... for other samples}` 
3) use `cell2location.run_cell2location(export_args={'img_key': None})` option

**Comment by yozhikoff** [comment] 2021-03-04 12:30
@onahman Setting GPU shouldn't be too hard, we have a short guide about it [here](https://github.com/BayraktarLab/cell2location#using-docker-image). The only potential issue is that it does require root access, is it a problem for you?

**Comment by onahman** [comment] 2021-03-04 12:52
@yozhikoff No, I have root access. I will check out the guide.
Thank you!

**Comment by vitkl** [comment] 2021-03-07 23:42
Hi @lopollar @sztankatt @onahman @yozhikoff !

This error was due to a bug in ` cell2location.run_cell2location` which failed to recognise the sparse matrix of all possible types and did not covert them to dense `np.array`. Sorry about this.

Now fixed in https://github.com/BayraktarLab/cell2location/commit/4e260ca3c5e657d3e6c97f5e98c761f5faed8d42

**Closed by vitkl** 2021-03-07 23:42 UTC

**Comment by sztankatt** [comment] 2021-03-15 13:55
@vitkl thank you!
